### PR TITLE
Added a textField and handling for 4 of its delegates

### PR DESCRIPTION
**Pull request by HassanSyedt**
**What**: Adding a new renderable component from iOS: UITextField

**Why**: It's an important native component that can be wrapped up pretty easily.

**How**: Changes were implemented in the manner of other renderable components, along with creating events for 4 delegates, textFieldDidEndEditing, textFieldDidBeginEditing, textFieldShouldClear, textFieldShouldReturn.

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x ] Ready to be merged 
- [ ] Added myself to contributors table 

Need to add the corresponding javascript part for this renderable component. If someone can let me know what needs to be done I can go ahead and add that piece as well as an update to the documents on how to use it.

### CODE REVIEW

**Comment by Sherman-Chen** [comment]
Hi,

Please refer to [#186] as guide on how to expose this module to the JS layer for instantiating. I believe `UITextField` maps to HTML `textarea`.

Please also be sure to add [guid](https://github.com/Sherman-Chen/syr/blob/465742691b96cb2b9743b02602fc5f0097558344/ios/SyrNative/SyrNative/SyrSwitch.m#L19) to the exposed component. 

Thanks for your contribution!

**Comment by HassanSyedt** [comment]
@Sherman-Chen what would be the need of the guid? As i'm not using the EventHandler to pass the event and instead using the components sendEventWithName instead.

**Comment by HassanSyedt** [comment]
@Sherman-Chen please let me know if these changes are what you requested.

**Comment by Sherman-Chen** [comment]
@dmikey would you like to do a final review/thumbs up prior to merging? everything looks good to me, thanks @HassanSyedt !

**Comment by dmikey** [comment]
Going to hold off on this, and judge if we need this in core. Will close so it doesn't go stale. We're almost finished with CLI and sub modules.

**Pull request closed without merging**
